development:
  adapter: mysql2
  database: hackkrk-ha-service
  username: root
  password:
  host: localhost
  encoding: utf8
  reconnect: true
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: hackkrk-ha-service
  username: root
  password: HackKrkIsAw3some
  host: 10.144.19.93
  encoding: utf8
  reconnect: true
  pool: 5
  timeout: 5000

